paths:
  input_folder: './input_data'
  output_folder: './output_data'
  dictionary_folder: './Dictionaries'

files:
  source_dataset : 'Scholar.csv'
  target_dataset : 'DBLP1.csv'
  source_dataset_dictionary : ''
  filtered_mapped_transformed_csv: 'filtered_mapped_transformed.csv'
  entity_resolution_results_csv: 'entity_resolution_results.csv'

thresholds:
  drop_na_threshold: 0.8

columns:
  address_column: 'adresse'
